@extends('template')
@section('header')
@include('parts.header',['transparent'=>'transparent'])
@endsection
@section('context')
@include('sections.section-home')
@include('parts.typhograpy')
@include('immobiles.immobile-carrousel')
@endsection